version: '3.1'

services:
  lasup:
    env_file:
      - .env
    image: danielricklin/lasup:latest
    ports:
      - 3000:3000
  lasuppoller:
    env_file:
      - .env
    image: danielricklin/lasuppoller:latest
  mongo:
    image: mongo
    command: [--auth]
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

volumes:
  mongo-data:
